// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package tutorial

import (
	"database/sql"
)

type Ingredient struct {
	ID          int32
	Name        sql.NullString
	Description sql.NullString
}

type Product struct {
	ID        int32
	BarCode   sql.NullInt32
	Name      sql.NullString
	Category  sql.NullString
	Rating    sql.NullInt32
	CreatedAt sql.NullTime
}

type ProductIngredient struct {
	ID           int32
	ProductID    sql.NullInt32
	IngredientID sql.NullInt32
}
